//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CardioSence.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class rsCardiologicalObjective {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal rsCardiologicalObjective() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CardioSence.Resources.rsCardiologicalObjective", typeof(rsCardiologicalObjective).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abdomen.
        /// </summary>
        public static string AbdominalStatusId {
            get {
                return ResourceManager.GetString("AbdominalStatusId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abdomen.
        /// </summary>
        public static string AbdominalStatusName {
            get {
                return ResourceManager.GetString("AbdominalStatusName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objective Examination Date.
        /// </summary>
        public static string CardiologicalObjectiveDate {
            get {
                return ResourceManager.GetString("CardiologicalObjectiveDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string CardiologicalObjectiveDrugId {
            get {
                return ResourceManager.GetString("CardiologicalObjectiveDrugId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string CardiologicalObjectiveId {
            get {
                return ResourceManager.GetString("CardiologicalObjectiveId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drug Frequency.
        /// </summary>
        public static string DrugFrequencyId {
            get {
                return ResourceManager.GetString("DrugFrequencyId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drug Frequency.
        /// </summary>
        public static string DrugFrequencyName {
            get {
                return ResourceManager.GetString("DrugFrequencyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drug.
        /// </summary>
        public static string DrugId {
            get {
                return ResourceManager.GetString("DrugId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drug.
        /// </summary>
        public static string DrugName {
            get {
                return ResourceManager.GetString("DrugName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        public static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heart Murmur.
        /// </summary>
        public static string HeartMurmurTypeId {
            get {
                return ResourceManager.GetString("HeartMurmurTypeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heart Murmur.
        /// </summary>
        public static string HeartMurmurTypeName {
            get {
                return ResourceManager.GetString("HeartMurmurTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heart Sound.
        /// </summary>
        public static string HeartSoundTypeId {
            get {
                return ResourceManager.GetString("HeartSoundTypeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heart Sound.
        /// </summary>
        public static string HeartSoundTypeName {
            get {
                return ResourceManager.GetString("HeartSoundTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LAD (Left Arteria Dorsalis Pedis).
        /// </summary>
        public static string LADArteriaStatusName {
            get {
                return ResourceManager.GetString("LADArteriaStatusName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LAD (Left Arteria Dorsalis Pedis).
        /// </summary>
        public static string LADPId {
            get {
                return ResourceManager.GetString("LADPId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Carotid Bruit.
        /// </summary>
        public static string LCBBruitName {
            get {
                return ResourceManager.GetString("LCBBruitName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Carotid Bruit.
        /// </summary>
        public static string LCBId {
            get {
                return ResourceManager.GetString("LCBId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liver.
        /// </summary>
        public static string LiverId {
            get {
                return ResourceManager.GetString("LiverId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liver.
        /// </summary>
        public static string LiverName {
            get {
                return ResourceManager.GetString("LiverName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right NIBP.
        /// </summary>
        public static string LNIBP {
            get {
                return ResourceManager.GetString("LNIBP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LRA (Left Radial Arteria).
        /// </summary>
        public static string LRAArteriaStatusName {
            get {
                return ResourceManager.GetString("LRAArteriaStatusName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LRA (Left Radial Arteria).
        /// </summary>
        public static string LRAId {
            get {
                return ResourceManager.GetString("LRAId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lung.
        /// </summary>
        public static string LungId {
            get {
                return ResourceManager.GetString("LungId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lung.
        /// </summary>
        public static string LungName {
            get {
                return ResourceManager.GetString("LungName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peryphery.
        /// </summary>
        public static string PeripherialStatusId {
            get {
                return ResourceManager.GetString("PeripherialStatusId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peryphery.
        /// </summary>
        public static string PeripherialStatusName {
            get {
                return ResourceManager.GetString("PeripherialStatusName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Physician.
        /// </summary>
        public static string PhysicianId {
            get {
                return ResourceManager.GetString("PhysicianId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Physician.
        /// </summary>
        public static string PhysicianName {
            get {
                return ResourceManager.GetString("PhysicianName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pulse.
        /// </summary>
        public static string Pulse {
            get {
                return ResourceManager.GetString("Pulse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RAD (Right Arteria Dorsalis Pedis).
        /// </summary>
        public static string RADArteriaStatusName {
            get {
                return ResourceManager.GetString("RADArteriaStatusName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RAD (Right Arteria Dorsalis Pedis).
        /// </summary>
        public static string RADPId {
            get {
                return ResourceManager.GetString("RADPId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Carotid Bruit.
        /// </summary>
        public static string RCBBruitName {
            get {
                return ResourceManager.GetString("RCBBruitName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Carotid Bruit.
        /// </summary>
        public static string RCBId {
            get {
                return ResourceManager.GetString("RCBId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right NIBP.
        /// </summary>
        public static string RNIBP {
            get {
                return ResourceManager.GetString("RNIBP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RRA (Right Radial Artery).
        /// </summary>
        public static string RRAArteriaStatusName {
            get {
                return ResourceManager.GetString("RRAArteriaStatusName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RRA (Right Radial Artery).
        /// </summary>
        public static string RRAId {
            get {
                return ResourceManager.GetString("RRAId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature.
        /// </summary>
        public static string Temperature {
            get {
                return ResourceManager.GetString("Temperature", resourceCulture);
            }
        }
    }
}
