//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CardioSence.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class rsCardiologicalCatheterization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal rsCardiologicalCatheterization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CardioSence.Resources.rsCardiologicalCatheterization", typeof(rsCardiologicalCatheterization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bypass (arterial).
        /// </summary>
        public static string ArterialBypass {
            get {
                return ResourceManager.GetString("ArterialBypass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catheterization Date.
        /// </summary>
        public static string CardiologicalCatheterizationDate {
            get {
                return ResourceManager.GetString("CardiologicalCatheterizationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string CardiologicalCatheterizationId {
            get {
                return ResourceManager.GetString("CardiologicalCatheterizationId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string CardiologicalCatheterizationSegmentId {
            get {
                return ResourceManager.GetString("CardiologicalCatheterizationSegmentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catheterization Image Path.
        /// </summary>
        public static string CatheterizationImageURL {
            get {
                return ResourceManager.GetString("CatheterizationImageURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catheterization Movie Path.
        /// </summary>
        public static string CatheterizationMovieURL {
            get {
                return ResourceManager.GetString("CatheterizationMovieURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proximal Cx.
        /// </summary>
        public static string Cx1 {
            get {
                return ResourceManager.GetString("Cx1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proximal Cx stenosis.
        /// </summary>
        public static string Cx1Stenosis {
            get {
                return ResourceManager.GetString("Cx1Stenosis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middele Cx.
        /// </summary>
        public static string Cx2 {
            get {
                return ResourceManager.GetString("Cx2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle Cx stenosis.
        /// </summary>
        public static string Cx2Stenosis {
            get {
                return ResourceManager.GetString("Cx2Stenosis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distal Cx.
        /// </summary>
        public static string Cx3 {
            get {
                return ResourceManager.GetString("Cx3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distal Cx stenosis.
        /// </summary>
        public static string Cx3Stenosis {
            get {
                return ResourceManager.GetString("Cx3Stenosis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First diagonal.
        /// </summary>
        public static string Diag1 {
            get {
                return ResourceManager.GetString("Diag1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First diagonal stenosis.
        /// </summary>
        public static string Diag1Stenosis {
            get {
                return ResourceManager.GetString("Diag1Stenosis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second diagonal.
        /// </summary>
        public static string Diag2 {
            get {
                return ResourceManager.GetString("Diag2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second diagonal stenosis.
        /// </summary>
        public static string Diag2Stenosis {
            get {
                return ResourceManager.GetString("Diag2Stenosis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dominance Type.
        /// </summary>
        public static string DominanceTypeId {
            get {
                return ResourceManager.GetString("DominanceTypeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dominance Type.
        /// </summary>
        public static string DominanceTypeName {
            get {
                return ResourceManager.GetString("DominanceTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proximal LAD.
        /// </summary>
        public static string LAD1 {
            get {
                return ResourceManager.GetString("LAD1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proximal LAD stenosis.
        /// </summary>
        public static string LAD1Stenosis {
            get {
                return ResourceManager.GetString("LAD1Stenosis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle LAD.
        /// </summary>
        public static string LAD2 {
            get {
                return ResourceManager.GetString("LAD2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle LAD stenosis.
        /// </summary>
        public static string LAD2Stenosis {
            get {
                return ResourceManager.GetString("LAD2Stenosis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distal LAD.
        /// </summary>
        public static string LAD3 {
            get {
                return ResourceManager.GetString("LAD3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distal LAD stenosis.
        /// </summary>
        public static string LAD3Stenosis {
            get {
                return ResourceManager.GetString("LAD3Stenosis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Main.
        /// </summary>
        public static string LM {
            get {
                return ResourceManager.GetString("LM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Main stenosis.
        /// </summary>
        public static string LMStenosis {
            get {
                return ResourceManager.GetString("LMStenosis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Ventricle End-Diastolic Pressure.
        /// </summary>
        public static string LVEDP {
            get {
                return ResourceManager.GetString("LVEDP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Ventricle End-Diastolic Volume.
        /// </summary>
        public static string LVEDV {
            get {
                return ResourceManager.GetString("LVEDV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Ventricle Ejection Fraction.
        /// </summary>
        public static string LVEF {
            get {
                return ResourceManager.GetString("LVEF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Ventricle End-Systolic Volume.
        /// </summary>
        public static string LVESV {
            get {
                return ResourceManager.GetString("LVESV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Ventriculography.
        /// </summary>
        public static string LVGraphy {
            get {
                return ResourceManager.GetString("LVGraphy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First OM (obtuse marginal).
        /// </summary>
        public static string OM1 {
            get {
                return ResourceManager.GetString("OM1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First OM stenosis.
        /// </summary>
        public static string OM1Stenosis {
            get {
                return ResourceManager.GetString("OM1Stenosis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second OM.
        /// </summary>
        public static string OM2 {
            get {
                return ResourceManager.GetString("OM2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second OM stenosis.
        /// </summary>
        public static string OM2Stenosis {
            get {
                return ResourceManager.GetString("OM2Stenosis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Third OM.
        /// </summary>
        public static string OM3 {
            get {
                return ResourceManager.GetString("OM3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Third OM stenosis.
        /// </summary>
        public static string OM3Stenosis {
            get {
                return ResourceManager.GetString("OM3Stenosis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forth OM.
        /// </summary>
        public static string OM4 {
            get {
                return ResourceManager.GetString("OM4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forth OM stenosis.
        /// </summary>
        public static string OM4Stenosis {
            get {
                return ResourceManager.GetString("OM4Stenosis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posterior Descendant Artery.
        /// </summary>
        public static string PDA {
            get {
                return ResourceManager.GetString("PDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDA stenosis.
        /// </summary>
        public static string PDAStenosis {
            get {
                return ResourceManager.GetString("PDAStenosis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Physician.
        /// </summary>
        public static string PhysicianId {
            get {
                return ResourceManager.GetString("PhysicianId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Physician.
        /// </summary>
        public static string PhysicianName {
            get {
                return ResourceManager.GetString("PhysicianName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Posterolateral.
        /// </summary>
        public static string PL1 {
            get {
                return ResourceManager.GetString("PL1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First PL stenosis.
        /// </summary>
        public static string PL1Stenosis {
            get {
                return ResourceManager.GetString("PL1Stenosis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second Posterolateral.
        /// </summary>
        public static string PL2 {
            get {
                return ResourceManager.GetString("PL2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second PL stenosis.
        /// </summary>
        public static string PL2Stenosis {
            get {
                return ResourceManager.GetString("PL2Stenosis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proximal RCA (right coronary artery).
        /// </summary>
        public static string RCA1 {
            get {
                return ResourceManager.GetString("RCA1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proximal RCA stenosis.
        /// </summary>
        public static string RCA1Stenosis {
            get {
                return ResourceManager.GetString("RCA1Stenosis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle RCA.
        /// </summary>
        public static string RCA2 {
            get {
                return ResourceManager.GetString("RCA2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle RCA stenosis.
        /// </summary>
        public static string RCA2Stenosis {
            get {
                return ResourceManager.GetString("RCA2Stenosis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distal RCA.
        /// </summary>
        public static string RCA3 {
            get {
                return ResourceManager.GetString("RCA3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distal RCA stenosis.
        /// </summary>
        public static string RCA3Stenosis {
            get {
                return ResourceManager.GetString("RCA3Stenosis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string ResidentId {
            get {
                return ResourceManager.GetString("ResidentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ramus Intermedianus.
        /// </summary>
        public static string Rm {
            get {
                return ResourceManager.GetString("Rm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rm stenosis.
        /// </summary>
        public static string RmStenosis {
            get {
                return ResourceManager.GetString("RmStenosis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Segment.
        /// </summary>
        public static string SegmentId {
            get {
                return ResourceManager.GetString("SegmentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Segment.
        /// </summary>
        public static string SegmentName {
            get {
                return ResourceManager.GetString("SegmentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size of Stenosis.
        /// </summary>
        public static string StenosisSize {
            get {
                return ResourceManager.GetString("StenosisSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bypass (venous).
        /// </summary>
        public static string VenousBypass {
            get {
                return ResourceManager.GetString("VenousBypass", resourceCulture);
            }
        }
    }
}
