//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CardioSence.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class rsCardiologicalPCI {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal rsCardiologicalPCI() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CardioSence.Resources.rsCardiologicalPCI", typeof(rsCardiologicalPCI).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bifurcation.
        /// </summary>
        public static string Bifurcation {
            get {
                return ResourceManager.GetString("Bifurcation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PCI Date.
        /// </summary>
        public static string CardiologicalPCIDate {
            get {
                return ResourceManager.GetString("CardiologicalPCIDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string CardiologicalPCIId {
            get {
                return ResourceManager.GetString("CardiologicalPCIId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string CardiologicalPCISegmentId {
            get {
                return ResourceManager.GetString("CardiologicalPCISegmentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direct Stent.
        /// </summary>
        public static string DirectStent {
            get {
                return ResourceManager.GetString("DirectStent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of the stent.
        /// </summary>
        public static string DrugElutionTypeId {
            get {
                return ResourceManager.GetString("DrugElutionTypeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of the stent.
        /// </summary>
        public static string DrugElutionTypeName {
            get {
                return ResourceManager.GetString("DrugElutionTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of Lesion.
        /// </summary>
        public static string LesionTypeId {
            get {
                return ResourceManager.GetString("LesionTypeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of Lesion.
        /// </summary>
        public static string LesionTypeName {
            get {
                return ResourceManager.GetString("LesionTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PCI Image Path.
        /// </summary>
        public static string PCIImageURL {
            get {
                return ResourceManager.GetString("PCIImageURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PCI Movie Path.
        /// </summary>
        public static string PCIMovieURL {
            get {
                return ResourceManager.GetString("PCIMovieURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Physician.
        /// </summary>
        public static string PhysicianId {
            get {
                return ResourceManager.GetString("PhysicianId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Physician.
        /// </summary>
        public static string PhysicianName {
            get {
                return ResourceManager.GetString("PhysicianName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string ResidentId {
            get {
                return ResourceManager.GetString("ResidentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restenosis.
        /// </summary>
        public static string Restenosis {
            get {
                return ResourceManager.GetString("Restenosis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Segment.
        /// </summary>
        public static string SegmentId {
            get {
                return ResourceManager.GetString("SegmentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Segment.
        /// </summary>
        public static string SegmentName {
            get {
                return ResourceManager.GetString("SegmentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stenosis (%).
        /// </summary>
        public static string StenosisPercentage {
            get {
                return ResourceManager.GetString("StenosisPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stent Ballon Size.
        /// </summary>
        public static string StentBallonSize {
            get {
                return ResourceManager.GetString("StentBallonSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stent.
        /// </summary>
        public static string StentId {
            get {
                return ResourceManager.GetString("StentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length of Stent.
        /// </summary>
        public static string Stentlength {
            get {
                return ResourceManager.GetString("Stentlength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stent.
        /// </summary>
        public static string StentName {
            get {
                return ResourceManager.GetString("StentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of Stent.
        /// </summary>
        public static string StentTypeId {
            get {
                return ResourceManager.GetString("StentTypeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of Stent.
        /// </summary>
        public static string StentTypeName {
            get {
                return ResourceManager.GetString("StentTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TIMIAId {
            get {
                return ResourceManager.GetString("TIMIAId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TimiAName {
            get {
                return ResourceManager.GetString("TimiAName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TIMIBId {
            get {
                return ResourceManager.GetString("TIMIBId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string TimiBName {
            get {
                return ResourceManager.GetString("TimiBName", resourceCulture);
            }
        }
    }
}
