//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CardioSence.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class rsCardiologicalSurgery {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal rsCardiologicalSurgery() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CardioSence.Resources.rsCardiologicalSurgery", typeof(rsCardiologicalSurgery).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ventilated Hours (additional).
        /// </summary>
        public static string AdditionalHoursVentilated {
            get {
                return ResourceManager.GetString("AdditionalHoursVentilated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time of Anaesthezia.
        /// </summary>
        public static string AnesthesiaTime {
            get {
                return ResourceManager.GetString("AnesthesiaTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APTT.
        /// </summary>
        public static string APTT {
            get {
                return ResourceManager.GetString("APTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bypass (B1).
        /// </summary>
        public static string B1BypassName {
            get {
                return ResourceManager.GetString("B1BypassName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Segment (B1).
        /// </summary>
        public static string B1SegmentName {
            get {
                return ResourceManager.GetString("B1SegmentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bypass (B2).
        /// </summary>
        public static string B2BypassName {
            get {
                return ResourceManager.GetString("B2BypassName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Segment (B2).
        /// </summary>
        public static string B2SegmentName {
            get {
                return ResourceManager.GetString("B2SegmentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bypass (B3).
        /// </summary>
        public static string B3BypasstName {
            get {
                return ResourceManager.GetString("B3BypasstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Segment (B3).
        /// </summary>
        public static string B3SegmentName {
            get {
                return ResourceManager.GetString("B3SegmentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bicarbonate.
        /// </summary>
        public static string BicarbonateTypeId {
            get {
                return ResourceManager.GetString("BicarbonateTypeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bicarbonate.
        /// </summary>
        public static string BicarbonateTypeName {
            get {
                return ResourceManager.GetString("BicarbonateTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hemorrhage Degree.
        /// </summary>
        public static string BloodLossVolume {
            get {
                return ResourceManager.GetString("BloodLossVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bypass (B1).
        /// </summary>
        public static string BypassB1Id {
            get {
                return ResourceManager.GetString("BypassB1Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bypass (B2).
        /// </summary>
        public static string BypassB2Id {
            get {
                return ResourceManager.GetString("BypassB2Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bypass (B3).
        /// </summary>
        public static string BypassB3Id {
            get {
                return ResourceManager.GetString("BypassB3Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bypass (C1).
        /// </summary>
        public static string BypassC1Id {
            get {
                return ResourceManager.GetString("BypassC1Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bypass (C2).
        /// </summary>
        public static string BypassC2Id {
            get {
                return ResourceManager.GetString("BypassC2Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bypass (C3).
        /// </summary>
        public static string BypassC3Id {
            get {
                return ResourceManager.GetString("BypassC3Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bypass Time.
        /// </summary>
        public static string BypassTime {
            get {
                return ResourceManager.GetString("BypassTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bypass (C1).
        /// </summary>
        public static string C1BypasstName {
            get {
                return ResourceManager.GetString("C1BypasstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Segment (C1).
        /// </summary>
        public static string C1SegmentName {
            get {
                return ResourceManager.GetString("C1SegmentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bypass (C2).
        /// </summary>
        public static string C2BypasstName {
            get {
                return ResourceManager.GetString("C2BypasstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Segment (C2).
        /// </summary>
        public static string C2SegmentName {
            get {
                return ResourceManager.GetString("C2SegmentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bypass (C3).
        /// </summary>
        public static string C3BypasstName {
            get {
                return ResourceManager.GetString("C3BypasstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Segment (C1).
        /// </summary>
        public static string C3SegmentName {
            get {
                return ResourceManager.GetString("C3SegmentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CABGX.
        /// </summary>
        public static string CABGX {
            get {
                return ResourceManager.GetString("CABGX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CaCl.
        /// </summary>
        public static string CaCl {
            get {
                return ResourceManager.GetString("CaCl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CaCl2.
        /// </summary>
        public static string CaCl2 {
            get {
                return ResourceManager.GetString("CaCl2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string CardiologicalSurgeryComplicationId {
            get {
                return ResourceManager.GetString("CardiologicalSurgeryComplicationId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surgery Date.
        /// </summary>
        public static string CardiologicalSurgeryDate {
            get {
                return ResourceManager.GetString("CardiologicalSurgeryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string CardiologicalSurgeryDrugId {
            get {
                return ResourceManager.GetString("CardiologicalSurgeryDrugId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string CardiologicalSurgeryId {
            get {
                return ResourceManager.GetString("CardiologicalSurgeryId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string CardiologicalSurgeryProcedureId {
            get {
                return ResourceManager.GetString("CardiologicalSurgeryProcedureId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string CardiologicalSurgeryValveId {
            get {
                return ResourceManager.GetString("CardiologicalSurgeryValveId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cardioplegia.
        /// </summary>
        public static string CardioplegiaTypeId {
            get {
                return ResourceManager.GetString("CardioplegiaTypeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cardioplegia.
        /// </summary>
        public static string CardioplegiaTypeName {
            get {
                return ResourceManager.GetString("CardioplegiaTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string ComplicationId {
            get {
                return ResourceManager.GetString("ComplicationId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complication.
        /// </summary>
        public static string ComplicationName {
            get {
                return ResourceManager.GetString("ComplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPB.
        /// </summary>
        public static string CPB {
            get {
                return ResourceManager.GetString("CPB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creatinine.
        /// </summary>
        public static string Creatinine {
            get {
                return ResourceManager.GetString("Creatinine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cross ClampTime.
        /// </summary>
        public static string CrossClampTime {
            get {
                return ResourceManager.GetString("CrossClampTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSD Length.
        /// </summary>
        public static string CSDLength {
            get {
                return ResourceManager.GetString("CSDLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Segment (D1).
        /// </summary>
        public static string D1SegmentName {
            get {
                return ResourceManager.GetString("D1SegmentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Segment (D2).
        /// </summary>
        public static string D2SegmentName {
            get {
                return ResourceManager.GetString("D2SegmentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Segment (D3).
        /// </summary>
        public static string D3SegmentName {
            get {
                return ResourceManager.GetString("D3SegmentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cause of Death.
        /// </summary>
        public static string DeathCauseId {
            get {
                return ResourceManager.GetString("DeathCauseId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cause of Death.
        /// </summary>
        public static string DeathCauseName {
            get {
                return ResourceManager.GetString("DeathCauseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Death.
        /// </summary>
        public static string DeathDate {
            get {
                return ResourceManager.GetString("DeathDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discharge Date.
        /// </summary>
        public static string DischargeDate {
            get {
                return ResourceManager.GetString("DischargeDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disease Type.
        /// </summary>
        public static string DiseaseStatusId {
            get {
                return ResourceManager.GetString("DiseaseStatusId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disease Type.
        /// </summary>
        public static string DiseaseStatusName {
            get {
                return ResourceManager.GetString("DiseaseStatusName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drug Frequency.
        /// </summary>
        public static string DrugFrequencyId {
            get {
                return ResourceManager.GetString("DrugFrequencyId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drug Frequency.
        /// </summary>
        public static string DrugFrequencyName {
            get {
                return ResourceManager.GetString("DrugFrequencyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string DrugId {
            get {
                return ResourceManager.GetString("DrugId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drug.
        /// </summary>
        public static string DrugName {
            get {
                return ResourceManager.GetString("DrugName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        public static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Euro SCORE.
        /// </summary>
        public static string EuroSCORE {
            get {
                return ResourceManager.GetString("EuroSCORE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extubated POD.
        /// </summary>
        public static string ExtubatedPOD {
            get {
                return ResourceManager.GetString("ExtubatedPOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F.
        /// </summary>
        public static string F {
            get {
                return ResourceManager.GetString("F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FFP Blood Product.
        /// </summary>
        public static string FFPBloodProductName {
            get {
                return ResourceManager.GetString("FFPBloodProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FFP CPB.
        /// </summary>
        public static string FFPCPB {
            get {
                return ResourceManager.GetString("FFPCPB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FFP.
        /// </summary>
        public static string FFPId {
            get {
                return ResourceManager.GetString("FFPId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GEL.
        /// </summary>
        public static string GEL {
            get {
                return ResourceManager.GetString("GEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gelofusin.
        /// </summary>
        public static string Gelofusin {
            get {
                return ResourceManager.GetString("Gelofusin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hb.
        /// </summary>
        public static string Hb {
            get {
                return ResourceManager.GetString("Hb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hct.
        /// </summary>
        public static string Hct {
            get {
                return ResourceManager.GetString("Hct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heparin.
        /// </summary>
        public static string Heparin1 {
            get {
                return ResourceManager.GetString("Heparin1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heparin.
        /// </summary>
        public static string Heparin2 {
            get {
                return ResourceManager.GetString("Heparin2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HFL.
        /// </summary>
        public static string HFL {
            get {
                return ResourceManager.GetString("HFL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ICU Length.
        /// </summary>
        public static string ICULength {
            get {
                return ResourceManager.GetString("ICULength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Implant.
        /// </summary>
        public static string ImplantId {
            get {
                return ResourceManager.GetString("ImplantId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Implant.
        /// </summary>
        public static string ImplantName {
            get {
                return ResourceManager.GetString("ImplantName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Implant Size.
        /// </summary>
        public static string ImplantSizeId {
            get {
                return ResourceManager.GetString("ImplantSizeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Implant Size.
        /// </summary>
        public static string ImplantSizeName {
            get {
                return ResourceManager.GetString("ImplantSizeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ventilated Hours (initial).
        /// </summary>
        public static string InitialHoursVentilated {
            get {
                return ResourceManager.GetString("InitialHoursVentilated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inotropic Support.
        /// </summary>
        public static string InotropicSupportId {
            get {
                return ResourceManager.GetString("InotropicSupportId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inotropic Support.
        /// </summary>
        public static string InotropicSupportName {
            get {
                return ResourceManager.GetString("InotropicSupportName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Patient Volume.
        /// </summary>
        public static string InPatientVolume {
            get {
                return ResourceManager.GetString("InPatientVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LFL.
        /// </summary>
        public static string LFL {
            get {
                return ResourceManager.GetString("LFL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liquid.
        /// </summary>
        public static string LiquidId {
            get {
                return ResourceManager.GetString("LiquidId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Man.
        /// </summary>
        public static string Man {
            get {
                return ResourceManager.GetString("Man", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mannitol.
        /// </summary>
        public static string Mannitol {
            get {
                return ResourceManager.GetString("Mannitol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medical Procedure.
        /// </summary>
        public static string MedicalProcedureId {
            get {
                return ResourceManager.GetString("MedicalProcedureId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medical Procedure.
        /// </summary>
        public static string MedicalProcedureName {
            get {
                return ResourceManager.GetString("MedicalProcedureName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mortality.
        /// </summary>
        public static string Mortality {
            get {
                return ResourceManager.GetString("Mortality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Na.
        /// </summary>
        public static string Na {
            get {
                return ResourceManager.GetString("Na", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NaCl.
        /// </summary>
        public static string NaCl {
            get {
                return ResourceManager.GetString("NaCl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NaHCO.
        /// </summary>
        public static string NaHCO {
            get {
                return ResourceManager.GetString("NaHCO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NaHCO3.
        /// </summary>
        public static string NaHCO3 {
            get {
                return ResourceManager.GetString("NaHCO3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string Other1 {
            get {
                return ResourceManager.GetString("Other1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string Other2 {
            get {
                return ResourceManager.GetString("Other2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PaCO2.
        /// </summary>
        public static string PaCO2 {
            get {
                return ResourceManager.GetString("PaCO2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PaO2.
        /// </summary>
        public static string PaO2 {
            get {
                return ResourceManager.GetString("PaO2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PH.
        /// </summary>
        public static string PH {
            get {
                return ResourceManager.GetString("PH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Platelet.
        /// </summary>
        public static string Platelet {
            get {
                return ResourceManager.GetString("Platelet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLT Blood Product.
        /// </summary>
        public static string PLTBloodProductName {
            get {
                return ResourceManager.GetString("PLTBloodProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLT.
        /// </summary>
        public static string PLTId {
            get {
                return ResourceManager.GetString("PLTId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potassium.
        /// </summary>
        public static string Potassium {
            get {
                return ResourceManager.GetString("Potassium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary Volume.
        /// </summary>
        public static string PrimaryVolume {
            get {
                return ResourceManager.GetString("PrimaryVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prothesis.
        /// </summary>
        public static string ProthesisId {
            get {
                return ResourceManager.GetString("ProthesisId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prothesis.
        /// </summary>
        public static string ProthesisName {
            get {
                return ResourceManager.GetString("ProthesisName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R.
        /// </summary>
        public static string R {
            get {
                return ResourceManager.GetString("R", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RBC Blood Product.
        /// </summary>
        public static string RBCBloodProductName {
            get {
                return ResourceManager.GetString("RBCBloodProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RBC CPB.
        /// </summary>
        public static string RBCCPB {
            get {
                return ResourceManager.GetString("RBCCPB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RBC.
        /// </summary>
        public static string RBCId {
            get {
                return ResourceManager.GetString("RBCId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReIntubation.
        /// </summary>
        public static string ReIntubation {
            get {
                return ResourceManager.GetString("ReIntubation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Residual Volume.
        /// </summary>
        public static string ResidualVolume {
            get {
                return ResourceManager.GetString("ResidualVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Segment (B1).
        /// </summary>
        public static string SegmentB1Id {
            get {
                return ResourceManager.GetString("SegmentB1Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Segment (B2).
        /// </summary>
        public static string SegmentB2Id {
            get {
                return ResourceManager.GetString("SegmentB2Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Segment (B3).
        /// </summary>
        public static string SegmentB3Id {
            get {
                return ResourceManager.GetString("SegmentB3Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Segment (C1).
        /// </summary>
        public static string SegmentC1Id {
            get {
                return ResourceManager.GetString("SegmentC1Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Segment (C2).
        /// </summary>
        public static string SegmentC2Id {
            get {
                return ResourceManager.GetString("SegmentC2Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Segment (C3).
        /// </summary>
        public static string SegmentC3Id {
            get {
                return ResourceManager.GetString("SegmentC3Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Segment (D1).
        /// </summary>
        public static string SegmentD1Id {
            get {
                return ResourceManager.GetString("SegmentD1Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Segment (D2).
        /// </summary>
        public static string SegmentD2Id {
            get {
                return ResourceManager.GetString("SegmentD2Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Segment (D3).
        /// </summary>
        public static string SegmentD3Id {
            get {
                return ResourceManager.GetString("SegmentD3Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skin Incision Close Time.
        /// </summary>
        public static string SkinIncisionCloseTime {
            get {
                return ResourceManager.GetString("SkinIncisionCloseTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skin Incision Start Time.
        /// </summary>
        public static string SkinIncisionStartTime {
            get {
                return ResourceManager.GetString("SkinIncisionStartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skin Temperature.
        /// </summary>
        public static string SkinTemperature {
            get {
                return ResourceManager.GetString("SkinTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sodium.
        /// </summary>
        public static string Sodium {
            get {
                return ResourceManager.GetString("Sodium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ventilated Hours (total).
        /// </summary>
        public static string TotalHoursVentilated {
            get {
                return ResourceManager.GetString("TotalHoursVentilated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Operation Time.
        /// </summary>
        public static string TotalOperationTime {
            get {
                return ResourceManager.GetString("TotalOperationTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Volume.
        /// </summary>
        public static string TotalVolume {
            get {
                return ResourceManager.GetString("TotalVolume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valve Surgery Type.
        /// </summary>
        public static string ValveSurgeryTypeId {
            get {
                return ResourceManager.GetString("ValveSurgeryTypeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valve Surgery Type.
        /// </summary>
        public static string ValveSurgeryTypeName {
            get {
                return ResourceManager.GetString("ValveSurgeryTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valve Type.
        /// </summary>
        public static string ValveTypeId {
            get {
                return ResourceManager.GetString("ValveTypeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valve Type.
        /// </summary>
        public static string ValveTypeName {
            get {
                return ResourceManager.GetString("ValveTypeName", resourceCulture);
            }
        }
    }
}
