//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CardioSence.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class rsCardiologicalDuplexScan {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal rsCardiologicalDuplexScan() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CardioSence.Resources.rsCardiologicalDuplexScan", typeof(rsCardiologicalDuplexScan).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplex Scan Date.
        /// </summary>
        public static string CardiologicalDuplexScanDate {
            get {
                return ResourceManager.GetString("CardiologicalDuplexScanDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string CardiologicalDuplexScanId {
            get {
                return ResourceManager.GetString("CardiologicalDuplexScanId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LCC Diameter.
        /// </summary>
        public static string LCCStenosisDM {
            get {
                return ResourceManager.GetString("LCCStenosisDM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LCC Status.
        /// </summary>
        public static string LCCStenosisId {
            get {
                return ResourceManager.GetString("LCCStenosisId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LCC Status.
        /// </summary>
        public static string LCCStenosisName {
            get {
                return ResourceManager.GetString("LCCStenosisName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to % of Normal.
        /// </summary>
        public static string LCCStenosisPC {
            get {
                return ResourceManager.GetString("LCCStenosisPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LCE Diameter.
        /// </summary>
        public static string LCEStenosisDM {
            get {
                return ResourceManager.GetString("LCEStenosisDM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LCE Status.
        /// </summary>
        public static string LCEStenosisId {
            get {
                return ResourceManager.GetString("LCEStenosisId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LCE Status.
        /// </summary>
        public static string LCEStenosisName {
            get {
                return ResourceManager.GetString("LCEStenosisName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to % of Normal.
        /// </summary>
        public static string LCEStenosisPC {
            get {
                return ResourceManager.GetString("LCEStenosisPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LCI Diameter.
        /// </summary>
        public static string LCIStenosisDM {
            get {
                return ResourceManager.GetString("LCIStenosisDM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LCI Status.
        /// </summary>
        public static string LCIStenosisId {
            get {
                return ResourceManager.GetString("LCIStenosisId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LCI Status.
        /// </summary>
        public static string LCIStenosisName {
            get {
                return ResourceManager.GetString("LCIStenosisName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to % of Normal.
        /// </summary>
        public static string LCIStenosisPC {
            get {
                return ResourceManager.GetString("LCIStenosisPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LSA Diameter.
        /// </summary>
        public static string LSAStenosisDM {
            get {
                return ResourceManager.GetString("LSAStenosisDM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LSA Status.
        /// </summary>
        public static string LSAStenosisId {
            get {
                return ResourceManager.GetString("LSAStenosisId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LSA Status.
        /// </summary>
        public static string LSAStenosisName {
            get {
                return ResourceManager.GetString("LSAStenosisName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to % of Normal.
        /// </summary>
        public static string LSAStenosisPC {
            get {
                return ResourceManager.GetString("LSAStenosisPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LVA Diameter.
        /// </summary>
        public static string LVAStenosisDM {
            get {
                return ResourceManager.GetString("LVAStenosisDM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LVA Status.
        /// </summary>
        public static string LVAStenosisId {
            get {
                return ResourceManager.GetString("LVAStenosisId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LVA Status.
        /// </summary>
        public static string LVAStenosisName {
            get {
                return ResourceManager.GetString("LVAStenosisName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to % of Normal.
        /// </summary>
        public static string LVAStenosisPC {
            get {
                return ResourceManager.GetString("LVAStenosisPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RCA Diameter.
        /// </summary>
        public static string RCAStenosisDM {
            get {
                return ResourceManager.GetString("RCAStenosisDM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RCA Status.
        /// </summary>
        public static string RCAStenosisId {
            get {
                return ResourceManager.GetString("RCAStenosisId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RCA Status.
        /// </summary>
        public static string RCAStenosisName {
            get {
                return ResourceManager.GetString("RCAStenosisName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to % of Normal.
        /// </summary>
        public static string RCAStenosisPC {
            get {
                return ResourceManager.GetString("RCAStenosisPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RCC Diameter.
        /// </summary>
        public static string RCCStenosisDM {
            get {
                return ResourceManager.GetString("RCCStenosisDM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RCC Status.
        /// </summary>
        public static string RCCStenosisId {
            get {
                return ResourceManager.GetString("RCCStenosisId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RCC Status.
        /// </summary>
        public static string RCCStenosisName {
            get {
                return ResourceManager.GetString("RCCStenosisName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to % of Normal.
        /// </summary>
        public static string RCCStenosisPC {
            get {
                return ResourceManager.GetString("RCCStenosisPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RCE Diameter.
        /// </summary>
        public static string RCEStenosisDM {
            get {
                return ResourceManager.GetString("RCEStenosisDM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RCE Status.
        /// </summary>
        public static string RCEStenosisId {
            get {
                return ResourceManager.GetString("RCEStenosisId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RCE Status.
        /// </summary>
        public static string RCEStenosisName {
            get {
                return ResourceManager.GetString("RCEStenosisName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to % of Normal.
        /// </summary>
        public static string RCEStenosisPC {
            get {
                return ResourceManager.GetString("RCEStenosisPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RCI Diameter.
        /// </summary>
        public static string RCIStenosisDM {
            get {
                return ResourceManager.GetString("RCIStenosisDM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RCI Status.
        /// </summary>
        public static string RCIStenosisId {
            get {
                return ResourceManager.GetString("RCIStenosisId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RCI Status.
        /// </summary>
        public static string RCIStenosisName {
            get {
                return ResourceManager.GetString("RCIStenosisName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to % of Normal.
        /// </summary>
        public static string RCIStenosisPC {
            get {
                return ResourceManager.GetString("RCIStenosisPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string ResidentId {
            get {
                return ResourceManager.GetString("ResidentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RVA Diameter.
        /// </summary>
        public static string RVAStenosisDM {
            get {
                return ResourceManager.GetString("RVAStenosisDM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RVA Status.
        /// </summary>
        public static string RVAStenosisId {
            get {
                return ResourceManager.GetString("RVAStenosisId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RVA Status.
        /// </summary>
        public static string RVAStenosisName {
            get {
                return ResourceManager.GetString("RVAStenosisName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to % of Normal.
        /// </summary>
        public static string RVAStenosisPC {
            get {
                return ResourceManager.GetString("RVAStenosisPC", resourceCulture);
            }
        }
    }
}
