//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CardioSence.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class rsCardiologicalExamination {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal rsCardiologicalExamination() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CardioSence.Resources.rsCardiologicalExamination", typeof(rsCardiologicalExamination).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alfa-Amylase.
        /// </summary>
        public static string AAmilaza {
            get {
                return ResourceManager.GetString("AAmilaza", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Albumin.
        /// </summary>
        public static string albumin {
            get {
                return ResourceManager.GetString("albumin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alanine Aminotransferase.
        /// </summary>
        public static string ALT {
            get {
                return ResourceManager.GetString("ALT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activated Partial Thromboplastin Time.
        /// </summary>
        public static string APTT {
            get {
                return ResourceManager.GetString("APTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anti-Streptolysin.
        /// </summary>
        public static string ASLO {
            get {
                return ResourceManager.GetString("ASLO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aspartate Aminotransferase.
        /// </summary>
        public static string AST {
            get {
                return ResourceManager.GetString("AST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basophil.
        /// </summary>
        public static string Basophil {
            get {
                return ResourceManager.GetString("Basophil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bilirubin (Direct).
        /// </summary>
        public static string BilirubinDirect {
            get {
                return ResourceManager.GetString("BilirubinDirect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bilirubin (Total).
        /// </summary>
        public static string BilirubinTotal {
            get {
                return ResourceManager.GetString("BilirubinTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blood group number.
        /// </summary>
        public static string BloodGroupId {
            get {
                return ResourceManager.GetString("BloodGroupId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blood group number.
        /// </summary>
        public static string BloodGroupName {
            get {
                return ResourceManager.GetString("BloodGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brucella Blood Agar.
        /// </summary>
        public static string BRUStatusId {
            get {
                return ResourceManager.GetString("BRUStatusId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brucella Blood Agar.
        /// </summary>
        public static string BRUStatusName {
            get {
                return ResourceManager.GetString("BRUStatusName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ca2+.
        /// </summary>
        public static string Calcium {
            get {
                return ResourceManager.GetString("Calcium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Examination Date.
        /// </summary>
        public static string CardiologicalExaminationDate {
            get {
                return ResourceManager.GetString("CardiologicalExaminationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string CardiologicalExaminationId {
            get {
                return ResourceManager.GetString("CardiologicalExaminationId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cholesterol.
        /// </summary>
        public static string Cholesterol {
            get {
                return ResourceManager.GetString("Cholesterol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creatine Kinase.
        /// </summary>
        public static string CK {
            get {
                return ResourceManager.GetString("CK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creatine Kinase MB- isoenzyme.
        /// </summary>
        public static string CKMB {
            get {
                return ResourceManager.GetString("CKMB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creatinine.
        /// </summary>
        public static string Creatinine {
            get {
                return ResourceManager.GetString("Creatinine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C Reactive Protein.
        /// </summary>
        public static string CRP {
            get {
                return ResourceManager.GetString("CRP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eosinophil.
        /// </summary>
        public static string Eosinophil {
            get {
                return ResourceManager.GetString("Eosinophil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erythrocyte Sedimentation Rate.
        /// </summary>
        public static string ESR {
            get {
                return ResourceManager.GetString("ESR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frailty Index.
        /// </summary>
        public static string FI {
            get {
                return ResourceManager.GetString("FI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fibrinogen.
        /// </summary>
        public static string Fibrinogen {
            get {
                return ResourceManager.GetString("Fibrinogen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glucose.
        /// </summary>
        public static string Glucose {
            get {
                return ResourceManager.GetString("Glucose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hemoglobin.
        /// </summary>
        public static string Hb {
            get {
                return ResourceManager.GetString("Hb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HBs Antigen Test.
        /// </summary>
        public static string HBSStatusId {
            get {
                return ResourceManager.GetString("HBSStatusId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HBs Antigen Test.
        /// </summary>
        public static string HBSStatusName {
            get {
                return ResourceManager.GetString("HBSStatusName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hematocrit.
        /// </summary>
        public static string HCT {
            get {
                return ResourceManager.GetString("HCT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hepatitis C Virus Blood Test.
        /// </summary>
        public static string HCVStatusId {
            get {
                return ResourceManager.GetString("HCVStatusId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hepatitis C Virus Blood Test.
        /// </summary>
        public static string HCVStatusName {
            get {
                return ResourceManager.GetString("HCVStatusName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High-Density Lipoprotein.
        /// </summary>
        public static string HDL {
            get {
                return ResourceManager.GetString("HDL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HIV.
        /// </summary>
        public static string HIVStatusId {
            get {
                return ResourceManager.GetString("HIVStatusId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HIV.
        /// </summary>
        public static string HIVStatusName {
            get {
                return ResourceManager.GetString("HIVStatusName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to International Normalized Ratio.
        /// </summary>
        public static string INR {
            get {
                return ResourceManager.GetString("INR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low-Density Lipoprotein.
        /// </summary>
        public static string LDL {
            get {
                return ResourceManager.GetString("LDL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leukocyte.
        /// </summary>
        public static string Leukocyte {
            get {
                return ResourceManager.GetString("Leukocyte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lymphocyte.
        /// </summary>
        public static string Lymphocyte {
            get {
                return ResourceManager.GetString("Lymphocyte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mean Hemoglobin Rate in Blood Cells.
        /// </summary>
        public static string MeanHbRBC {
            get {
                return ResourceManager.GetString("MeanHbRBC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metamyelocyte.
        /// </summary>
        public static string Metamyelocyte {
            get {
                return ResourceManager.GetString("Metamyelocyte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monocyte.
        /// </summary>
        public static string Monocyte {
            get {
                return ResourceManager.GetString("Monocyte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Myelocyte.
        /// </summary>
        public static string Myelocyte {
            get {
                return ResourceManager.GetString("Myelocyte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prothrombin Index.
        /// </summary>
        public static string PI {
            get {
                return ResourceManager.GetString("PI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thrombocyte.
        /// </summary>
        public static string Platelete {
            get {
                return ResourceManager.GetString("Platelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to K+.
        /// </summary>
        public static string Potassium {
            get {
                return ResourceManager.GetString("Potassium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protein (Total).
        /// </summary>
        public static string ProteinTotal {
            get {
                return ResourceManager.GetString("ProteinTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prothrombin Time.
        /// </summary>
        public static string PT {
            get {
                return ResourceManager.GetString("PT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red Blood Cell.
        /// </summary>
        public static string RBC {
            get {
                return ResourceManager.GetString("RBC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string ResidentId {
            get {
                return ResourceManager.GetString("ResidentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rheumatoid factor.
        /// </summary>
        public static string RF {
            get {
                return ResourceManager.GetString("RF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rh Factor Number.
        /// </summary>
        public static string RhFactorId {
            get {
                return ResourceManager.GetString("RhFactorId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rh Factor Number.
        /// </summary>
        public static string RhFactorName {
            get {
                return ResourceManager.GetString("RhFactorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Segmented Leukocyte.
        /// </summary>
        public static string SegmentedLeukocyte {
            get {
                return ResourceManager.GetString("SegmentedLeukocyte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Na+.
        /// </summary>
        public static string Sodium {
            get {
                return ResourceManager.GetString("Sodium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stab Leukocyte.
        /// </summary>
        public static string StabLeukocyte {
            get {
                return ResourceManager.GetString("StabLeukocyte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Triiodothyronine.
        /// </summary>
        public static string T3 {
            get {
                return ResourceManager.GetString("T3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tetraiodothyroxine.
        /// </summary>
        public static string T4 {
            get {
                return ResourceManager.GetString("T4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preponema Pallidum Haemagglutination Test.
        /// </summary>
        public static string TPHAStatusId {
            get {
                return ResourceManager.GetString("TPHAStatusId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preponema Pallidum Haemagglutination Test.
        /// </summary>
        public static string TPHAStatusName {
            get {
                return ResourceManager.GetString("TPHAStatusName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Triglyceride.
        /// </summary>
        public static string Triglyceride {
            get {
                return ResourceManager.GetString("Triglyceride", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Troponin.
        /// </summary>
        public static string TroponinStatusId {
            get {
                return ResourceManager.GetString("TroponinStatusId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Troponin.
        /// </summary>
        public static string TroponinStatusName {
            get {
                return ResourceManager.GetString("TroponinStatusName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thyreotropic hormone.
        /// </summary>
        public static string TTH {
            get {
                return ResourceManager.GetString("TTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Urea.
        /// </summary>
        public static string Urea {
            get {
                return ResourceManager.GetString("Urea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uric Acid.
        /// </summary>
        public static string UricAcid {
            get {
                return ResourceManager.GetString("UricAcid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Urine Cylinders.
        /// </summary>
        public static string UrineCylinderStatusId {
            get {
                return ResourceManager.GetString("UrineCylinderStatusId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Urine Cylinders.
        /// </summary>
        public static string UrineCylinderStatusName {
            get {
                return ResourceManager.GetString("UrineCylinderStatusName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Urine Density.
        /// </summary>
        public static string UrineDensity {
            get {
                return ResourceManager.GetString("UrineDensity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Urine Erithrocyte.
        /// </summary>
        public static string UrineErithrocyte {
            get {
                return ResourceManager.GetString("UrineErithrocyte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Urine Leucocyte.
        /// </summary>
        public static string UrineLeucocyte {
            get {
                return ResourceManager.GetString("UrineLeucocyte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Urine Microorganisms.
        /// </summary>
        public static string UrineMicroorganismStatusId {
            get {
                return ResourceManager.GetString("UrineMicroorganismStatusId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Urine Microorganisms.
        /// </summary>
        public static string UrineMicroorganismStatusName {
            get {
                return ResourceManager.GetString("UrineMicroorganismStatusName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Urine Protein.
        /// </summary>
        public static string UrineProtein {
            get {
                return ResourceManager.GetString("UrineProtein", resourceCulture);
            }
        }
    }
}
