//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CardioSence.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class rsCardiologicalCase {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal rsCardiologicalCase() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CardioSence.Resources.rsCardiologicalCase", typeof(rsCardiologicalCase).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alcohol Usage.
        /// </summary>
        public static string AlcoholUsageId {
            get {
                return ResourceManager.GetString("AlcoholUsageId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alcohol Usage.
        /// </summary>
        public static string AlcoholUsageName {
            get {
                return ResourceManager.GetString("AlcoholUsageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blood Cholesterol.
        /// </summary>
        public static string BloodCholesterolId {
            get {
                return ResourceManager.GetString("BloodCholesterolId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BloodCholesterol.
        /// </summary>
        public static string BloodCholesterolName {
            get {
                return ResourceManager.GetString("BloodCholesterolName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BMI.
        /// </summary>
        public static string BMI {
            get {
                return ResourceManager.GetString("BMI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BSA.
        /// </summary>
        public static string BSA {
            get {
                return ResourceManager.GetString("BSA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CAD.
        /// </summary>
        public static string CAD {
            get {
                return ResourceManager.GetString("CAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadiomyopathy.
        /// </summary>
        public static string CadiomyopathyId {
            get {
                return ResourceManager.GetString("CadiomyopathyId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadiomyopathy.
        /// </summary>
        public static string CadiomyopathyName {
            get {
                return ResourceManager.GetString("CadiomyopathyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadiomyopathy.
        /// </summary>
        public static string CadiomyopathyStatus {
            get {
                return ResourceManager.GetString("CadiomyopathyStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string CardiologicalCaseComplianId {
            get {
                return ResourceManager.GetString("CardiologicalCaseComplianId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string CardiologicalCaseDiseaseId {
            get {
                return ResourceManager.GetString("CardiologicalCaseDiseaseId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string CardiologicalCaseDrugId {
            get {
                return ResourceManager.GetString("CardiologicalCaseDrugId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string CardiologicalCaseId {
            get {
                return ResourceManager.GetString("CardiologicalCaseId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string CardiologicalCaseInvasionId {
            get {
                return ResourceManager.GetString("CardiologicalCaseInvasionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genetical Factors.
        /// </summary>
        public static string CardiologicalInheritance {
            get {
                return ResourceManager.GetString("CardiologicalInheritance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CATD.
        /// </summary>
        public static string CATDId {
            get {
                return ResourceManager.GetString("CATDId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CATD.
        /// </summary>
        public static string CATDName {
            get {
                return ResourceManager.GetString("CATDName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CATD.
        /// </summary>
        public static string CATDStatus {
            get {
                return ResourceManager.GetString("CATDStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CCS.
        /// </summary>
        public static string CCSId {
            get {
                return ResourceManager.GetString("CCSId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CCS.
        /// </summary>
        public static string CCSName {
            get {
                return ResourceManager.GetString("CCSName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CCS.
        /// </summary>
        public static string CCSStatus {
            get {
                return ResourceManager.GetString("CCSStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHD.
        /// </summary>
        public static string CHDId {
            get {
                return ResourceManager.GetString("CHDId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHD.
        /// </summary>
        public static string CHDName {
            get {
                return ResourceManager.GetString("CHDName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHD.
        /// </summary>
        public static string CHDStatus {
            get {
                return ResourceManager.GetString("CHDStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menopause.
        /// </summary>
        public static string ClimaxStatusId {
            get {
                return ResourceManager.GetString("ClimaxStatusId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menopause.
        /// </summary>
        public static string ClimaxStatusName {
            get {
                return ResourceManager.GetString("ClimaxStatusName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string ComplianId {
            get {
                return ResourceManager.GetString("ComplianId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complians.
        /// </summary>
        public static string ComplianName {
            get {
                return ResourceManager.GetString("ComplianName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultation Date.
        /// </summary>
        public static string ConsultationDate {
            get {
                return ResourceManager.GetString("ConsultationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COPD.
        /// </summary>
        public static string COPDId {
            get {
                return ResourceManager.GetString("COPDId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COPD.
        /// </summary>
        public static string COPDName {
            get {
                return ResourceManager.GetString("COPDName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Death Cause.
        /// </summary>
        public static string DeathCauseId {
            get {
                return ResourceManager.GetString("DeathCauseId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Death Cause.
        /// </summary>
        public static string DeathCauseName {
            get {
                return ResourceManager.GetString("DeathCauseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of Death.
        /// </summary>
        public static string DeathDate {
            get {
                return ResourceManager.GetString("DeathDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place of Death.
        /// </summary>
        public static string DeathOrganizationId {
            get {
                return ResourceManager.GetString("DeathOrganizationId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place of Death.
        /// </summary>
        public static string DeathOrganizationName {
            get {
                return ResourceManager.GetString("DeathOrganizationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Death.
        /// </summary>
        public static string DeathStatus {
            get {
                return ResourceManager.GetString("DeathStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dental Disease.
        /// </summary>
        public static string DentalDiseaseId {
            get {
                return ResourceManager.GetString("DentalDiseaseId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dental Disease.
        /// </summary>
        public static string DentalDiseaseName {
            get {
                return ResourceManager.GetString("DentalDiseaseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diabetes Mellitus.
        /// </summary>
        public static string DiabetesMellitusStatus {
            get {
                return ResourceManager.GetString("DiabetesMellitusStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discharge Date.
        /// </summary>
        public static string DischargeDate {
            get {
                return ResourceManager.GetString("DischargeDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disease Date.
        /// </summary>
        public static string DiseaseDate {
            get {
                return ResourceManager.GetString("DiseaseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string DiseaseId {
            get {
                return ResourceManager.GetString("DiseaseId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disease.
        /// </summary>
        public static string DiseaseName {
            get {
                return ResourceManager.GetString("DiseaseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string DiseaseStatusId {
            get {
                return ResourceManager.GetString("DiseaseStatusId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disease Status.
        /// </summary>
        public static string DiseaseStatusName {
            get {
                return ResourceManager.GetString("DiseaseStatusName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string DrugFrequencyId {
            get {
                return ResourceManager.GetString("DrugFrequencyId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drug Frequency.
        /// </summary>
        public static string DrugFrequencyName {
            get {
                return ResourceManager.GetString("DrugFrequencyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string DrugId {
            get {
                return ResourceManager.GetString("DrugId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drug.
        /// </summary>
        public static string DrugName {
            get {
                return ResourceManager.GetString("DrugName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        public static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string GastrointestinalDiseaseId {
            get {
                return ResourceManager.GetString("GastrointestinalDiseaseId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gastrointestinal Disease.
        /// </summary>
        public static string GastrointestinalDiseaseName {
            get {
                return ResourceManager.GetString("GastrointestinalDiseaseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gastrointestinal Disease.
        /// </summary>
        public static string GastrointestinalDiseaseStatus {
            get {
                return ResourceManager.GetString("GastrointestinalDiseaseStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glucose.
        /// </summary>
        public static string Glucose {
            get {
                return ResourceManager.GetString("Glucose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HB.
        /// </summary>
        public static string HBCriteriaId {
            get {
                return ResourceManager.GetString("HBCriteriaId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HB.
        /// </summary>
        public static string HBCriteriaName {
            get {
                return ResourceManager.GetString("HBCriteriaName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HB.
        /// </summary>
        public static string HBCriteriaStatus {
            get {
                return ResourceManager.GetString("HBCriteriaStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        public static string Height {
            get {
                return ResourceManager.GetString("Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HIT.
        /// </summary>
        public static string HITId {
            get {
                return ResourceManager.GetString("HITId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HIT.
        /// </summary>
        public static string HITName {
            get {
                return ResourceManager.GetString("HITName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HIT.
        /// </summary>
        public static string HITStatus {
            get {
                return ResourceManager.GetString("HITStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HVD.
        /// </summary>
        public static string HVDId {
            get {
                return ResourceManager.GetString("HVDId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HVD.
        /// </summary>
        public static string HVDName {
            get {
                return ResourceManager.GetString("HVDName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HVD.
        /// </summary>
        public static string HVDStatus {
            get {
                return ResourceManager.GetString("HVDStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hypertension Duration.
        /// </summary>
        public static string HypertensionDurationId {
            get {
                return ResourceManager.GetString("HypertensionDurationId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hypertension Duration.
        /// </summary>
        public static string HypertensionDurationName {
            get {
                return ResourceManager.GetString("HypertensionDurationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hypertension Duration.
        /// </summary>
        public static string HypertensionStatus {
            get {
                return ResourceManager.GetString("HypertensionStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Immunological Status.
        /// </summary>
        public static string ImmunologicalStatus {
            get {
                return ResourceManager.GetString("ImmunologicalStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Immunological Status.
        /// </summary>
        public static string ImmunologicalStatusId {
            get {
                return ResourceManager.GetString("ImmunologicalStatusId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Immunological Status.
        /// </summary>
        public static string ImmunologicalStatusName {
            get {
                return ResourceManager.GetString("ImmunologicalStatusName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Immunosuppressive Therapy.
        /// </summary>
        public static string ImmunosuppressiveTherapyStatus {
            get {
                return ResourceManager.GetString("ImmunosuppressiveTherapyStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infectious Endocarditis.
        /// </summary>
        public static string InfectiousEndocarditisId {
            get {
                return ResourceManager.GetString("InfectiousEndocarditisId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infectious Endocarditis.
        /// </summary>
        public static string InfectiousEndocarditisName {
            get {
                return ResourceManager.GetString("InfectiousEndocarditisName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Infectious Endocarditis.
        /// </summary>
        public static string InfectiousEndocarditisStatus {
            get {
                return ResourceManager.GetString("InfectiousEndocarditisStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Hospital.
        /// </summary>
        public static string InHospital {
            get {
                return ResourceManager.GetString("InHospital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invasion Date.
        /// </summary>
        public static string InvasionDate {
            get {
                return ResourceManager.GetString("InvasionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string InvasionId {
            get {
                return ResourceManager.GetString("InvasionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invasion.
        /// </summary>
        public static string InvasionName {
            get {
                return ResourceManager.GetString("InvasionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Diagnose.
        /// </summary>
        public static string MainDiagnose {
            get {
                return ResourceManager.GetString("MainDiagnose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mortality.
        /// </summary>
        public static string MortalityTypeId {
            get {
                return ResourceManager.GetString("MortalityTypeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mortality.
        /// </summary>
        public static string MortalityTypeName {
            get {
                return ResourceManager.GetString("MortalityTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Physical Activity.
        /// </summary>
        public static string MovementStatusId {
            get {
                return ResourceManager.GetString("MovementStatusId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Physical Activity.
        /// </summary>
        public static string MovementStatusName {
            get {
                return ResourceManager.GetString("MovementStatusName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NYHA.
        /// </summary>
        public static string NYHAId {
            get {
                return ResourceManager.GetString("NYHAId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NYHA.
        /// </summary>
        public static string NYHAName {
            get {
                return ResourceManager.GetString("NYHAName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization.
        /// </summary>
        public static string OrganizationId {
            get {
                return ResourceManager.GetString("OrganizationId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization.
        /// </summary>
        public static string OrganizationName {
            get {
                return ResourceManager.GetString("OrganizationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Disease.
        /// </summary>
        public static string OtherDiseaseId {
            get {
                return ResourceManager.GetString("OtherDiseaseId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Disease.
        /// </summary>
        public static string OtherDiseaseName {
            get {
                return ResourceManager.GetString("OtherDiseaseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out Patient.
        /// </summary>
        public static string OutPatient {
            get {
                return ResourceManager.GetString("OutPatient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pulmonary Disease.
        /// </summary>
        public static string PulmonaryDiseaseId {
            get {
                return ResourceManager.GetString("PulmonaryDiseaseId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pulmonary Disease.
        /// </summary>
        public static string PulmonaryDiseaseName {
            get {
                return ResourceManager.GetString("PulmonaryDiseaseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pulmonary Disease.
        /// </summary>
        public static string PulmonaryDiseaseStatus {
            get {
                return ResourceManager.GetString("PulmonaryDiseaseStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PVDT.
        /// </summary>
        public static string PVDTId {
            get {
                return ResourceManager.GetString("PVDTId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PVDT.
        /// </summary>
        public static string PVDTName {
            get {
                return ResourceManager.GetString("PVDTName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PVDT.
        /// </summary>
        public static string PVDTStatus {
            get {
                return ResourceManager.GetString("PVDTStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referral Organization.
        /// </summary>
        public static string ReferralOrganizationId {
            get {
                return ResourceManager.GetString("ReferralOrganizationId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referral Organization.
        /// </summary>
        public static string ReferralOrganizationName {
            get {
                return ResourceManager.GetString("ReferralOrganizationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resuscitation.
        /// </summary>
        public static string ResuscitationStatus {
            get {
                return ResourceManager.GetString("ResuscitationStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rheumatizm Duration.
        /// </summary>
        public static string RheumatismStatus {
            get {
                return ResourceManager.GetString("RheumatismStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rheumatizm Duration.
        /// </summary>
        public static string RheumatizmDurationId {
            get {
                return ResourceManager.GetString("RheumatizmDurationId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rheumatizm Duration.
        /// </summary>
        public static string RheumatizmDurationName {
            get {
                return ResourceManager.GetString("RheumatizmDurationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shock Type.
        /// </summary>
        public static string ShockTypeId {
            get {
                return ResourceManager.GetString("ShockTypeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shock Type.
        /// </summary>
        public static string ShockTypeName {
            get {
                return ResourceManager.GetString("ShockTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shock Type.
        /// </summary>
        public static string ShockTypeStatus {
            get {
                return ResourceManager.GetString("ShockTypeStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smoking Status.
        /// </summary>
        public static string SmokingStatusId {
            get {
                return ResourceManager.GetString("SmokingStatusId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smoking Status.
        /// </summary>
        public static string SmokingStatusName {
            get {
                return ResourceManager.GetString("SmokingStatusName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smoking Frequency.
        /// </summary>
        public static string SmokingTypeId {
            get {
                return ResourceManager.GetString("SmokingTypeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smoking Frequency.
        /// </summary>
        public static string SmokingTypeName {
            get {
                return ResourceManager.GetString("SmokingTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Strokes.
        /// </summary>
        public static string StroceCount {
            get {
                return ResourceManager.GetString("StroceCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stroke Type.
        /// </summary>
        public static string StrokeStatus {
            get {
                return ResourceManager.GetString("StrokeStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stroke Type.
        /// </summary>
        public static string StrokeTypeId {
            get {
                return ResourceManager.GetString("StrokeTypeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stroke Type.
        /// </summary>
        public static string StrokeTypeName {
            get {
                return ResourceManager.GetString("StrokeTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treatment Type.
        /// </summary>
        public static string TreatmentTypeId {
            get {
                return ResourceManager.GetString("TreatmentTypeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treatment Type.
        /// </summary>
        public static string TreatmentTypeName {
            get {
                return ResourceManager.GetString("TreatmentTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Urogenitalic Disease.
        /// </summary>
        public static string UrogenitalicDiseaseId {
            get {
                return ResourceManager.GetString("UrogenitalicDiseaseId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Urogenitalic Disease.
        /// </summary>
        public static string UrogenitalicDiseaseName {
            get {
                return ResourceManager.GetString("UrogenitalicDiseaseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Urogenitalic Disease.
        /// </summary>
        public static string UrogenitalicDiseaseStatus {
            get {
                return ResourceManager.GetString("UrogenitalicDiseaseStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight.
        /// </summary>
        public static string Weight {
            get {
                return ResourceManager.GetString("Weight", resourceCulture);
            }
        }
    }
}
