//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CardioSence.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class rsCardiologicalCPB {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal rsCardiologicalCPB() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CardioSence.Resources.rsCardiologicalCPB", typeof(rsCardiologicalCPB).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACT.
        /// </summary>
        public static string ACT {
            get {
                return ResourceManager.GetString("ACT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BE-B.
        /// </summary>
        public static string BEB {
            get {
                return ResourceManager.GetString("BEB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BE-B Type.
        /// </summary>
        public static string BebTypeId {
            get {
                return ResourceManager.GetString("BebTypeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BE-B Type.
        /// </summary>
        public static string BebTypeName {
            get {
                return ResourceManager.GetString("BebTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blood Urea Nitrogen.
        /// </summary>
        public static string BUN {
            get {
                return ResourceManager.GetString("BUN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ca++.
        /// </summary>
        public static string Ca {
            get {
                return ResourceManager.GetString("Ca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string CardiologicalCPBId {
            get {
                return ResourceManager.GetString("CardiologicalCPBId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cl-.
        /// </summary>
        public static string Cl {
            get {
                return ResourceManager.GetString("Cl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPB Date.
        /// </summary>
        public static string CPBDate {
            get {
                return ResourceManager.GetString("CPBDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPB Time.
        /// </summary>
        public static string CPBTime {
            get {
                return ResourceManager.GetString("CPBTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fraction of Inspired O2.
        /// </summary>
        public static string FiO2 {
            get {
                return ResourceManager.GetString("FiO2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glucosa.
        /// </summary>
        public static string Glucosa {
            get {
                return ResourceManager.GetString("Glucosa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hemoglobin.
        /// </summary>
        public static string Hb {
            get {
                return ResourceManager.GetString("Hb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HCO3-.
        /// </summary>
        public static string HCO3 {
            get {
                return ResourceManager.GetString("HCO3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hematocrit.
        /// </summary>
        public static string Ht {
            get {
                return ResourceManager.GetString("Ht", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ion Gap.
        /// </summary>
        public static string IonGap {
            get {
                return ResourceManager.GetString("IonGap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to K+.
        /// </summary>
        public static string K {
            get {
                return ResourceManager.GetString("K", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lactosa.
        /// </summary>
        public static string Lactosa {
            get {
                return ResourceManager.GetString("Lactosa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAP.
        /// </summary>
        public static string MAP {
            get {
                return ResourceManager.GetString("MAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mg++.
        /// </summary>
        public static string Mg {
            get {
                return ResourceManager.GetString("Mg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Na+.
        /// </summary>
        public static string Na {
            get {
                return ResourceManager.GetString("Na", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pCO2.
        /// </summary>
        public static string pCO2 {
            get {
                return ResourceManager.GetString("pCO2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PH.
        /// </summary>
        public static string pH {
            get {
                return ResourceManager.GetString("pH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pO2.
        /// </summary>
        public static string pO2 {
            get {
                return ResourceManager.GetString("pO2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rectal T.
        /// </summary>
        public static string RectalTemperature {
            get {
                return ResourceManager.GetString("RectalTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string ResidentId {
            get {
                return ResourceManager.GetString("ResidentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample Type.
        /// </summary>
        public static string SampleTypeId {
            get {
                return ResourceManager.GetString("SampleTypeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample Type.
        /// </summary>
        public static string SampleTypeName {
            get {
                return ResourceManager.GetString("SampleTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O2 Saturation.
        /// </summary>
        public static string SO2 {
            get {
                return ResourceManager.GetString("SO2", resourceCulture);
            }
        }
    }
}
