//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CardioSence.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class rsCardiologicalECG {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal rsCardiologicalECG() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CardioSence.Resources.rsCardiologicalECG", typeof(rsCardiologicalECG).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heart Axis.
        /// </summary>
        public static string AxisDegree {
            get {
                return ResourceManager.GetString("AxisDegree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BBB.
        /// </summary>
        public static string BBBId {
            get {
                return ResourceManager.GetString("BBBId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth Date.
        /// </summary>
        public static string BirthDate {
            get {
                return ResourceManager.GetString("BirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ECG Date.
        /// </summary>
        public static string CardiologicalECGDate {
            get {
                return ResourceManager.GetString("CardiologicalECGDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string CardiologicalECGId {
            get {
                return ResourceManager.GetString("CardiologicalECGId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conduction Disturbance.
        /// </summary>
        public static string ConductionDisturbanceId {
            get {
                return ResourceManager.GetString("ConductionDisturbanceId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conduction Disturbance.
        /// </summary>
        public static string ConductionDisturbanceName {
            get {
                return ResourceManager.GetString("ConductionDisturbanceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heart Rate.
        /// </summary>
        public static string HR {
            get {
                return ResourceManager.GetString("HR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laun.
        /// </summary>
        public static string LaunId {
            get {
                return ResourceManager.GetString("LaunId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laun.
        /// </summary>
        public static string LaunName {
            get {
                return ResourceManager.GetString("LaunName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Ventricule Hypertrophy.
        /// </summary>
        public static string LVHId {
            get {
                return ResourceManager.GetString("LVHId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PAC.
        /// </summary>
        public static string PAC {
            get {
                return ResourceManager.GetString("PAC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient ID.
        /// </summary>
        public static string PatientId {
            get {
                return ResourceManager.GetString("PatientId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PQ Interval.
        /// </summary>
        public static string PQ {
            get {
                return ResourceManager.GetString("PQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QT Interval.
        /// </summary>
        public static string QT {
            get {
                return ResourceManager.GetString("QT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string ResidentFirstName {
            get {
                return ResourceManager.GetString("ResidentFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string ResidentId {
            get {
                return ResourceManager.GetString("ResidentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string ResidentLastName {
            get {
                return ResourceManager.GetString("ResidentLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Patient Name.
        /// </summary>
        public static string ResidentName {
            get {
                return ResourceManager.GetString("ResidentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle Name.
        /// </summary>
        public static string ResidentPatronymicName {
            get {
                return ResourceManager.GetString("ResidentPatronymicName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rhythm Type.
        /// </summary>
        public static string RhythmTypeID {
            get {
                return ResourceManager.GetString("RhythmTypeID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rhythm Type.
        /// </summary>
        public static string RhythmTypeName {
            get {
                return ResourceManager.GetString("RhythmTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Ventricule Hypertrophy.
        /// </summary>
        public static string RVHId {
            get {
                return ResourceManager.GetString("RVHId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Ventricule Hypertrophy.
        /// </summary>
        public static string RVHName {
            get {
                return ResourceManager.GetString("RVHName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Ventricule Hypertrophy.
        /// </summary>
        public static string VHName {
            get {
                return ResourceManager.GetString("VHName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zone of Infarction.
        /// </summary>
        public static string ZoneInfarctionId {
            get {
                return ResourceManager.GetString("ZoneInfarctionId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zone of Ishemia.
        /// </summary>
        public static string ZoneIshemiaId {
            get {
                return ResourceManager.GetString("ZoneIshemiaId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zone of Ishemia.
        /// </summary>
        public static string ZoneName {
            get {
                return ResourceManager.GetString("ZoneName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zone of Infarction.
        /// </summary>
        public static string ZoneName1 {
            get {
                return ResourceManager.GetString("ZoneName1", resourceCulture);
            }
        }
    }
}
