//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CardioSence.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class rsCardiologicalEchoCG {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal rsCardiologicalEchoCG() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CardioSence.Resources.rsCardiologicalEchoCG", typeof(rsCardiologicalEchoCG).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aortic Diameter.
        /// </summary>
        public static string AOD {
            get {
                return ResourceManager.GetString("AOD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area of Stenosis.
        /// </summary>
        public static string Area {
            get {
                return ResourceManager.GetString("Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Echocardiography Date.
        /// </summary>
        public static string CardiologicalEchoCGDate {
            get {
                return ResourceManager.GetString("CardiologicalEchoCGDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string CardiologicalEchoCGId {
            get {
                return ResourceManager.GetString("CardiologicalEchoCGId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Echocardiography FIle.
        /// </summary>
        public static string CardiologicalEchoCGMoviePath {
            get {
                return ResourceManager.GetString("CardiologicalEchoCGMoviePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string CardiologicalEchoCGVelocityId {
            get {
                return ResourceManager.GetString("CardiologicalEchoCGVelocityId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string CardiologicalEchoCGWallId {
            get {
                return ResourceManager.GetString("CardiologicalEchoCGWallId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wall Contractility.
        /// </summary>
        public static string ContractilityId {
            get {
                return ResourceManager.GetString("ContractilityId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wall Contractility.
        /// </summary>
        public static string ContractilityName {
            get {
                return ResourceManager.GetString("ContractilityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Echocardiography Zone.
        /// </summary>
        public static string EchoCGZoneId {
            get {
                return ResourceManager.GetString("EchoCGZoneId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Echocardiography Zone.
        /// </summary>
        public static string EchoCGZoneName {
            get {
                return ResourceManager.GetString("EchoCGZoneName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ejection Fraction.
        /// </summary>
        public static string EF {
            get {
                return ResourceManager.GetString("EF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gradient.
        /// </summary>
        public static string Gradient {
            get {
                return ResourceManager.GetString("Gradient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insufficiency.
        /// </summary>
        public static string InsufficiencyId {
            get {
                return ResourceManager.GetString("InsufficiencyId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insufficiency.
        /// </summary>
        public static string InsufficiencyName {
            get {
                return ResourceManager.GetString("InsufficiencyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IVSW*.
        /// </summary>
        public static string IVSW {
            get {
                return ResourceManager.GetString("IVSW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Atrial Diameter.
        /// </summary>
        public static string LAD {
            get {
                return ResourceManager.GetString("LAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Ventricular Diastolic Diameter.
        /// </summary>
        public static string LVDD {
            get {
                return ResourceManager.GetString("LVDD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Ventricular Diastolic Volume.
        /// </summary>
        public static string LVDV {
            get {
                return ResourceManager.GetString("LVDV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Ventricle Posterior Wall.
        /// </summary>
        public static string LVPW {
            get {
                return ResourceManager.GetString("LVPW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Ventricular Systolic Diameter.
        /// </summary>
        public static string LVSD {
            get {
                return ResourceManager.GetString("LVSD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left Ventricular Stroke Volume.
        /// </summary>
        public static string LVSV {
            get {
                return ResourceManager.GetString("LVSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mean PAP.
        /// </summary>
        public static string MenaPAP {
            get {
                return ResourceManager.GetString("MenaPAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PA AcT/ET.
        /// </summary>
        public static string PAACTET {
            get {
                return ResourceManager.GetString("PAACTET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peak PAP.
        /// </summary>
        public static string PeakPAP {
            get {
                return ResourceManager.GetString("PeakPAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PAS*.
        /// </summary>
        public static string PericardialAnteriorSeparation {
            get {
                return ResourceManager.GetString("PericardialAnteriorSeparation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string ResidentId {
            get {
                return ResourceManager.GetString("ResidentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right Ventricular Diastolic Diameter.
        /// </summary>
        public static string RVDD {
            get {
                return ResourceManager.GetString("RVDD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stenosis.
        /// </summary>
        public static string StenosisId {
            get {
                return ResourceManager.GetString("StenosisId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stenosis.
        /// </summary>
        public static string StenosisName {
            get {
                return ResourceManager.GetString("StenosisName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SV*.
        /// </summary>
        public static string SV {
            get {
                return ResourceManager.GetString("SV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valve.
        /// </summary>
        public static string ValveId {
            get {
                return ResourceManager.GetString("ValveId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valve.
        /// </summary>
        public static string ValveName {
            get {
                return ResourceManager.GetString("ValveName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valve Velocity.
        /// </summary>
        public static string Velocity {
            get {
                return ResourceManager.GetString("Velocity", resourceCulture);
            }
        }
    }
}
